### ISSUE TITLE
Certain dependent binaries are missing from the project.

### ISSUE THREAD

**Issue by santakdalai90** [ducalpha/SOP_Generator#1]
Certain binaries are missing from the project. I got this error while running it. 

```
$ python2 ./generator.py
pdflatex.exe -synctex=1 -interaction=nonstopmode university_of_michigan_computer_science_and_engineering_Duc.SOP.tex
Traceback (most recent call last):
  File "./generator.py", line 120, in <module>
    generator.generate_pdf()
  File "./generator.py", line 40, in generate_pdf
    self.generate_specific_pdf()
  File "./generator.py", line 47, in generate_specific_pdf
    call(pdflatex_cmd.split(' '))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ducalpha** [comment]
Thank you for the report. I am traveling and will look at it as soon as I settled down.
